build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related Prod APIs  "
  contactDetails:
    name: "Agustin Lara - Product Owner"
    email: "Agustin.l@outlook.com"
  onCallSupport:
    -(888) 555 1234
    -(888) 523 1345
