build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs reviewing the last part of externalized configuration test"  
  contactDetails:
    name: "Adrian R - QA Lead asdasda"
    email: "adrian.r@outlook.com"
  onCallSupport:
    -(777) 555 1234
    -(777) 523 1345
