build:
  version: "7.0"

loans:
  message: "Welcome to Eazy Bank loans related Prod APIs, reviewing if the refresh change works"
  contactDetails:
    name: "Calamarino Elegante"
    email: "calamarino.elegante@outlook.com"
  onCallSupport:
    - (556) 534 - 3496
    - (334) 687 - 9458
